ДЗ 1
Anastasiya04012000/2020-2-Atom-QA-Python-A-Gresova pull request #1
Opened 2020-09-30 18:20 UTC by Anastasiya04012000

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
*
*
*

2020-09-30 18:25 UTC, Anastasiya04012000 commented
Привет,  

Работу я заливала не со своего компьютера (мой компьютер не тянет PC, пишу с компьютера парня), поэтому указываются 2 участника

2020-10-08 04:01 UTC, SK1995 requested changes
В целом неплохо, оставил несколько комментариев.

Прошу особенно обратить внимание на комментарий про скоуп фикстур.

2020-10-08 04:01 UTC, SK1995 commented on tests/test_dict.py
> +def random_dict(scope='class'):
Тут лучше использовать `scope='function'`.
Скоуп фикстуры служит для того, чтобы обозначить, сколько времени будет жить объект, который она возвращает.
Сейчас выходит так, что у `random_dict` скоуп класса, из чего следует, что объект, который она возращает, будет _одинаковым_ для всех тестов внутри одного класса.

2020-10-08 04:01 UTC, SK1995 commented on tests/test_int.py
> +def random_value2():
Чтобы не приходилось так копировать фикстуры из файла в файл, можно определить их в `conftest.py`.

2020-10-08 04:01 UTC, SK1995 commented on tests/test_int.py
> +    def test(self, random_value1, random_value2):
Тестам лучше давать осмысленные названия, чтобы потом не запутаться в логике проверок.
Это скорее на будущее.

2020-10-08 04:01 UTC, SK1995 commented on tests/test_set.py
> +    yield set(list)
Можно сразу тут возвращать сет, минуя его генерацию через список:
`yield {random.randint(-1000, 1000) for _ in range(10)}`

2020-10-08 04:01 UTC, SK1995 commented on tests/test_set.py
> +        Set_union = random_set1.union(random_set2)
Ну почему с `Set_union` большой буквы-то :)
Вот [тут ](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) можно почитать про общепринятый стиль PEP8 и конкретно про то, какие переменные как писать.

Очень рекомендую посматривать на проверки линтера и пайчарма, у нас это даже в задании было написано.

2020-10-16 23:12 UTC, SK1995 approved these changes

2020-10-16 23:13 UTC, SK1995 commented
Много времени прошло, вроде никакой активности нет, поставил 3 балла из 4.
1 снял за комментарии выше.

2020-10-16 23:13 UTC, merged